version: '2'
services:
    presta-app:
        image: presta
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://presta-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=presta
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=presta-elasticsearch:9300
        ports:
            - 8080:8080
    presta-mongodb:
        extends:
            file: mongodb.yml
            service: presta-mongodb
    presta-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: presta-elasticsearch
